### ISSUE TITLE
train error (nccl) torch.distributed

### ISSUE THREAD

**Issue by bis70** [megvii-research/ECCV2022-RIFE#280]
I think your work is great. Unfortunately I do not manage to train the NN. The following error message appears in the console:

(rife) PS C:\Users\C\PycharmProjects\RIFE> python -m torch.distributed.launch --nproc_per_node=1 train.py --world_size=1

Traceback (most recent call last):
  File "train.py", line 146, in <module>
    torch.distributed.init_process_group(backend="nccl", world_size=args.world_size)
AttributeError: module 'torch.distributed' has no attribute 'init_process_group'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\rife\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\rife\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\rife\lib\site-packages\torch\distributed\launch.py", line 261, in <module>
    main()
  File "C:\ProgramData\Anaconda3\envs\rife\lib\site-packages\torch\distributed\launch.py", line 256, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['C:\\ProgramData\\Anaconda3\\envs\\rife\\python.exe', '-u', 'train.py', '--local_rank=0', '--world_size=1']' returned non-zero exit status 1.

**Comment by hzwer** [comment]
Please check https://github.com/pytorch/examples/issues/467. It seems to be a OS-torch related issue.

**Comment by bis70** [comment]
The link leads to a MacOS problem, I use Windows. Well maybe I will find the problem somewhere else

**Comment by Felix3322** [comment]
This is an automated reply and does not represent the author's views.
Due to long inactivity and no new actionable information, this issue will be closed automatically for now.
If you want to reopen, please reply with $reopen and include updated reproduction details/logs.
If you need a human maintainer to step in, please @hzwer.
